module.exports = {
  content: ["./*.html","./src/**/*.js"],
  safelist: [
    'fixed',
    'absolute',
    'relative',
    'inset-0',
    'left-0',
    '-bottom-0.5',
    '-bottom-[20px]',
    'top-0',
    'z-50',
    'z-[100]',
    'z-[1000]',
  
    'flex',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-center',
    'justify-between',
    'mx-auto',
    'ml-auto',
    'gap-2',
    'space-y-2',
    'w-full',
    'w-2/3',
    'max-h-[95vh]',
    'max-h-0',
    'h-screen',
    'h-px',
    'sm:max-w-[90vw]',
    'md:max-w-[800px]',
    'lg:max-w-[1000px]',
  
    'p-4',
    'sm:p-6',
    'md:p-8',
    'lg:p-[40px]',
    'py-2',
    'py-2.5',
    'px-3',
    'px-4',
    'px-5',
    'mt-2',
    'mt-6',
    'lg:mt-[30px]',
    'mr-[10]',
  
    'font-medium',
    'font-[merri]',
    'text-white',
    'text-gray-300',
    'text-purple-300',
    'text-green-300',
    'text-yellow-300',
    'text-[20px]',
    'text-[14px]',
    'text-[28px]',
    'text-[40px]',
    'text-[500%]',
    'tracking-[-5px]',
    'opacity-0',
    'opacity-75',
    'invisible',
    'lg:opacity-0',
  
    'bg-black',
    'bg-opacity-50',
    'bg-gray-800',
    'bg-[#99aab5]',
    'bg-[#23272a]',
    'bg-purple-500/10',
    'bg-green-500/10',
    'bg-yellow-500/10',
    'from-blue-500/10',
    'to-purple-500/10',
    'border-white/10',
    'border-[#333333]',
    'hover:border-white/20',
  
    'transition-all',
    'transition-opacity',
    'transition-transform',
    'duration-300',
    'duration-500',
    'duration-1000',
    'ease-in-out',
    'ease-linear',
    'transform',
    'hover:scale-90',
    'hover:scale-105',
    'group-hover:scale-90',
    'group-hover:scale-105',
    'hover:-translate-y-1',
    'group-hover:translate-x-1',
  
    'hover:text-gray-300',
    'hover:bg-blue-500/20',
    'hover:shadow-lg',
    'hover:shadow-blue-500/10',
    'group',
    'group/link',
    'group/btn',
    'group-hover/link',
    'group-hover/btn',
    'group-hover:text-blue-400',
    'group-hover:text-gray-200',
  
    'overflow-hidden',
    'overflow-y-auto',
    'rounded',
    'rounded-xl',
    'sm:gap-8',
  
    'fadeout',
    'slide-in',
    'slide-in-left',
    'slide-in-right',
    'slide-in-delay'
  ],
  
  theme: {
    extend: {
      colors: {
        customBackground: '#51434b',
        customGrey: '#99aab5',
      },
    },
    fontFamily: {
      'it': ['it', 'sans-serif'],
      'mont': ['mont', 'sans-serif'],
      'montM': ['montM', 'sans-serif'],
      'montL': ['montL', 'sans-serif'],
      'lmr': ['lmr', 'sans-serif'],
      'merri': ['merri', 'sans-serif']
    },
  },
  plugins: [],

}
